### PR TITLE
more commands for EB3A working (for Enum only prepared, not working so far)

### PR DESCRIPTION
**Pull request by giovanne123**
additional commands for the EB3A are working:
image

for the commands with enum values some work needed (help welcome ;-)
e.g. in DEVICE_EB3A.h
```
enum ChargingMode {
   STANDARD = 0,
    SILENT = 1,
    TURBO = 2
};
```
if using this way, throwing error while compiling - therefore so far commented out
```
static device_field_data_t bluetti_device_command[] = {
  /*Page 0x00 Core */
  {AC_OUTPUT_ON,      0x0B, 0xBF, 1, 0, 0, BOOL_FIELD}, 
  {DC_OUTPUT_ON,      0x0B, 0xC0, 1, 0, 0, BOOL_FIELD},
  //{LED_MODE,          0x0B, 0xDA, 1, 0, 0, LedMode},
  {POWER_OFF,         0x0B, 0xF4, 1, 0, 0, BOOL_FIELD},
  {ECO_ON,            0x0B, 0xF7, 1, 0, 0, BOOL_FIELD},
  //{ECO_SHUTDOWN,      0x0B, 0xF8, 1, 0, 0, EcoShutdown},
--> throwing error:  {CHARGING_MODE,     0x0B, 0xF9, 1, 0, 0, ChargingMode},
  {POWER_LIFTING_ON,  0x0B, 0xFA, 1, 0, 0, BOOL_FIELD}
};
```

### CODE REVIEW

**Comment by giovanne123** [comment]
Pull no longer needed, outdated for me. Implemented already additionals for EB3A in main branch (quick and dirty ;-))

(next looking for additional "bluetti_device_state[]" in "DEVICE_EB3A.h" for "LED_MODE", "POWER_LIFTING_ON", .... to use this in HA state topic)

**Comment by mariolukas** [comment]
> Pull no longer needed, outdated for me. Implemented already additionals for EB3A in main branch (quick and dirty ;-))
> 
> (next looking for additional "bluetti_device_state[]" in "DEVICE_EB3A.h" for "LED_MODE", "POWER_LIFTING_ON", .... to use this in HA state topic)

A RP would still be nice for the EB3A changes.

**Comment by giovanne123** [comment]
> > Pull no longer needed, outdated for me. Implemented already additionals for EB3A in main branch (quick and dirty ;-))
> > (next looking for additional "bluetti_device_state[]" in "DEVICE_EB3A.h" for "LED_MODE", "POWER_LIFTING_ON", .... to use this in HA state topic)
> 
> A RP would still be nice for the EB3A changes.

Right, need some time to detail needed parts...

For the moment I have separated my Quick &Dirty code https://github.com/giovanne123/EB3A_Bluetti_ESP32_HA  (derived from yours) because I need it running and I have implemented too much EB3A related and for my special use case (Servo Power Switch, HA, ...)

**Comment by SmokyBob** [comment]
Eb3a owner too, I might have time tomorrow to look at @giovanne123 branch and integrate only the minimum changes needed to have the commands working (my battery is not being used now, just logging solar generation).
Would love to have them working before continuing working on my custom stuff (telegram bot remote control)

**Pull request closed without merging**
